### ISSUE TITLE
zooz 4-in1 sensor

### ISSUE THREAD

**Issue by pcgirl** [krlaframboise/SmartThings#10]
I am using your device handler for this motion sensor and it is working great!  Thank you!  However, when I try to setup a piston in CoRE and I try to set the illuminance setting, CoRE uses Lux but the device handler is using % of light.  Anyway to get the illuminance to work correctly in CoRE?

**Comment by krlaframboise** [comment]
The engineers provided a conversion chart, but the numbers didn't seem right so I wasn't comfortable building that conversion into my DTH.

The next version of the device will report in lux so I planned on waiting a few months for the new device, but since I'll have to work out a conversion for the old firmware anyways, I might as well do it now.

I just put the device next to a different motion sensor that reports in lux and I'm logging all their events with the Simple Event Logger SmartApp. I'll review the data this weekend to see if the numbers align with that conversion chart and if they don't, I'll come up with my own conversion.

I'll most likely release a new version this weekend that has an option for reporting in lux. If you don't want to wait you can try one of the other device handlers on the forum because I think at least one of them uses that conversion chart and reports in lux.

**Comment by krlaframboise** [comment]
I just released a new version that allows you to report the light level as either lux or %.  I've also added a lux offset adjustment you can use if it appears to always be reporting low or high.

_The conversion is based off of 1,000+ events from 5 sensors, but I'm still not that confident with the accuracy so as soon as I get a 3rd type of device that reports lux I'll revisit the calculation and make adjustments if needed._
