### ISSUE TITLE
Learning seems not working well

### ISSUE THREAD

**Issue by jacksun101** [krlaframboise/SmartThings#19]
I can only learn key for the first time. If I learn the second key, no matter I've tried it failed. Please see the logs below. I pressed the Learn button, and then tap the EP2. But then two buttons turned to default mode, and nothing happened.

// Pressed the EP2 Button
4:26:21: trace Executing pushLearn()
4:26:21: debug Cancelling Learning because button 2 was pushed while learning button 1

// Pressed the Learn button
4:26:14: debug Learning On Push Button (1-9)
4:26:13: trace Executing pushLearn()

**Comment by krlaframboise** [comment]
SmartThings broke the ability to set state values to null on 10/11/2017 which is most likely why that feature isn't working, but since you mentioned tapping "EP2" after the "Learn" button I'm going to explain how the learn feature is supposed to work.

The buttons EP1 - EP6 at the top allow you to switch between the 6 "End Points" and for each end point you can program 9 buttons.  If you use the optional SmartApp with this device you can use each End Point as a seperate device in SmartThings.

If you're trying to program buttons for EP2 you should tap the "EP2" button before tapping the "Learn" button.

I just released a new version with a workaround for the SmartThings bug so if you upgrade to the latest version of the DTH everything should work as expected.

**Comment by jacksun101** [comment]
Thank you so much for providing this awesome device handler and smartapp, and it's working good now. And thanks for your explain, it was my bad mentioning the EP2 Button, what I meant is the 9 buttons.
