### ISSUE TITLE
Logging events from previous dates

### ISSUE THREAD

**Issue by ShreyaPrasad31** [krlaframboise/SmartThings#27]
Great work! I was wondering if there is a way to log events from previous weeks that are already present on the smart things hub. The google sheet starts reading from the day the app is published in the smart things hub.

**Comment by krlaframboise** [comment]
I ran into issues with the application timing out if it tries to retrieve too many events the first time it runs so it only goes back 3 hours.

It's not possible to go back more than 7 days because SmartThings only keeps the event history for the last 7 days.

If you make the change below and install a new instance of the SmartApp it will retrieve the events for the last 7 days.  

Change line 555 to:
	def firstRunMS = (7 * 24 * 60 * 60 * 1000) // 7 Days

Because of the time out problem it also limits each device to 200 events per execution so to capture 7 days worth of events you might need to also change line 767 to something like:
	return settings?.maxEvents ?: 5000 

If you have a lot of devices or your devices have a lot of events then those changes will most likely cause it to time out so you'll probably have to tweak those lines until it successfully logs for the first time.
