### ISSUE TITLE
Zooz Power Switch missing voltage

### ISSUE THREAD

**Issue by chucko88** [krlaframboise/SmartThings#37]
Kevin,
As always, thanks for the great DTH's.  I got a Zooz Zen15 a couple months ago and have just been running the default ST handler until now.  I finally got some free time to play and switched over to your Zooz Power Switch DTH to see what I've been missing.  Everything looked great except no current or voltage display.  I played with the default reporting parameters and quickly got a response from everything except the voltage display after saving again.  After giving it time to update all of the parameters and trying different reporting timings, voltage was still a no show.  I uncommented the log.trace and started watching the log to see if it was being reported at all but never saw voltage.  Looking at my device view, I noticed that there was no state variable for voltage either.  

Since voltage rarely changes much, I wondered if your change a couple months ago to comment out "isStateChange: True" had prevented the creation of a variable for voltage in the first place, given that I hadn't had such a state variable when using the ST DTH.  So I uncommented the isStateChange line and sure enough, my voltage showed up immediately.  So I think the DTH needs a slight tweak for new users to make sure all state variable get created with a value in the first place before avoiding adding duplicate events for numbers that rarely change.

Thanks

**Comment by krlaframboise** [comment]
If 2 handlers support the Voltage Measurement capability and you switch from one handler to the other, the voltage events generated by the first handler don't get lost because they're attached to the device and not the handler.

When isStateChange is not specified, SmartThings won't create the event if the new value is the same as the old value, but it will create the event if there isn't an old value.  That list is originally empty so if an attribute had to be in the list in order for it to create the event then no events would ever get created when isStateChange is not specified.

Tapping refresh, possibly more than once, most likely would have solved the problem without having to make that change.  There are also several other factors that could have played a role in what you were seeing, but no one else has reported this problem so it's not worth spending time trying to figure it out.

I'm closing the issue, but I appreciate you taking the time to create it and if the problem comes up again I'll consider re-opening it.

**Comment by chucko88** [comment]
Thanks for looking at this.  When it happened, I played with it for over an
hour and a half, setting refresh rate down to one minute and watching it
over and over.  I changed just about every setting and would watch to see
if it registered voltage.  The old device handler I used didn't have a
state variable for voltage so it wasn't there to disappear.  I read all all
your noteson changes so I just thought I would add that one back to see if
there was any effect and the voltage state variable immediately popped up
and was populated so I just thought I'd let you know what I saw happen in
case anyone else may also note something similar.
Thanks for all your work that you share.
Chuck
