### ISSUE TITLE
Dome - Smartthings:. Chime not working

### ISSUE THREAD

**Issue by skamanj** [krlaframboise/SmartThings#40]
I just installed and connected my done Siren, and the interface has changed.  There is no longer any option for a chime, just strobe, siren, or siren + strobe.  Any clue?

**Comment by krlaframboise** [comment]
The fingerprint in this handler is identical to the one in the built-in handler, but sometimes the device gets assigned the built-in handler instead of mine.

Open the device in the IDE and verify that the "Type" field is set to my handler which will be located in the custom section at the very bottom of the list.

The custom UI only works in the classic mobile app so if you're using the new mobile app then you won't see any of those features.  

ST is supposed to be opening that functionality up to developers within the next few months, but at the moment there's nothing I can do about it so you need to use the classic mobile app if you want the custom UI.
