### ISSUE TITLE
Cannot create device handler

### ISSUE THREAD

**Issue by RetiredOldCat** [krlaframboise/SmartThings#5]
I copied and pasted the code for Aeon Labs Doorbell into the 'From Code' option, and received this error message:

Org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed: script14738009978891708824013.groovy: 107: expecting '}', found ',' @ line 107, column 27. 107 attribute "lastPoll", "number" ^ 1 error

Can you help?

**Comment by krlaframboise** [comment]
It looks like you either copied content from the GitHub page that's not part of the code or didn't copy all of the code.  It's really easy to make that mistake so make sure you always click the RAW button before copying because that will open a page that just displays the code.

The other most common copy and paste problem is that users try creating a device handler from the "My SmartApps" section of the IDE instead of the "My Device Types", but I don't believe that's your issue.

**Comment by RetiredOldCat** [comment]
Bingo!  Thanks Kevin; that did the trick.  All I have to do now is fine tune it.  tnx, mg

**Comment by krlaframboise** [comment]
I have 2 device handlers on GitHub for the Aeon Labs Doorbell, but make sure you're using the one called "Aeotec Doorbell".

I've merged the functionality of both into that device handler and I'm no longer supporting the old "multifunction" version.

**Comment by RetiredOldCat** [comment]
The one I’m using works great.  I hate to trouble you, but I want to use mine as a soft alarm (so it doesn’t blow me out of a dead sleep).  Is there a way to defeat the 20 second limit for playing MP3’s, so I can retire it manually?  Tnx, mg

**Comment by krlaframboise** [comment]
That's a hardware setting that can't be changed.

Once I've wrapped up a few other projects I'm working on, I might add a schedule track feature that allows you to get around the 20 second limit, but it's probably going to be a while.

If you use the SmartApp CoRE, you can setup a "FOR LOOP" with a 10 second delay that plays the track.  In theory, if you're track is 20 seconds they should overlap and play for more than 20 seconds without any gaps.
