### ISSUE TITLE
No issue.. Help please? 

### ISSUE THREAD

**Issue by ddrill2021** [krlaframboise/SmartThings#56]
Hi, 

My IT team is unavailable to assist with my problem until July, so they suggested I follow the instructions below. I've done that but my data is not showing up in the google sheet. The only thing I can identify that might be wrong is the arbitrary: "Maximum number of events to log for each device per section: When the SmartApp Executes it retrieves between (1 and 50) events from the device since it last ran depending on this setting. Setting this number too high may cause the SmartApp to reach the 20 second execution limit and setting it too low may result in some events not getting logged." I am not an IT person and I have no idea how to troubleshoot or even beginning finding out why. Can anyone help?

**Comment by krlaframboise** [comment]
SmartThings changed the way they handle events/state changes so the SImple Event Logger SmartApp doesn't work anymore for most users.

The link below is for another SmartApp that logs events to Google sheets and it captures them instead of retrieving them from the history so it shouldn't have been impacted by the change that broke mine.

The description was deleted from that Forum Topic so I'm not sure if it works, but it might be worth checking out.

https://github.com/loverso-smartthings/googleDocsLogging
