### ISSUE TITLE
How to add new sensor type?

### ISSUE THREAD

**Issue by tkswkdaos** [krlaframboise/SmartThings#57]
Hello, I am a non-professional in the field of coding. We are using the application you provided us to do research on the current indoor environment.

I am using an air monitor officially released by Samsung (ACM-B1M0S).
In addition, we plan to add a door sensor if possible.

In this situation, if someone want to log PM2.5 (also PM10, PM1.0) sensor value and door open/close, or another sensor, what part of the provided code can be changed?!

Also, I set the logging event to 1 hour in the SmartThings application on my smartphone, but I need help in a situation where data is being sent to the sheet every 15 minutes. I'm asking if it's possible to send data every hour on the hour.(00:00:00, 01:00:00, 02:00:00, ...)

Sorry for the basic and unprofessional question. Thank you for providing a useful application. It's a cumbersome question, but if you answer it when you have time, it will be of great help.

**Comment by krlaframboise** [comment]
I wrote this SmartApp to capture all events sent by the device, but there's another SmartApp that captures just the most recent event so that would probably work better for what you're trying to do...

https://community.smartthings.com/t/log-events-to-google-sheets-see-post-36719-154-for-current-github-repo-and-v1-1/36719/154?u=krlaframboise
