### ISSUE TITLE
Zooz Zen76 switch driver is not working

### ISSUE THREAD

**Issue by tkralphs** [krlaframboise/SmartThings#59]
I have several of these switches on firmware version 1.03 and just bought a new one with firmware version 10.00. None of them seem to work with the custom driver (at least with my v2 hub). In particular, when attempting to power on or off from the app, the operation times out and reports a network error. The switches with the 1.03 firmware all work fine with the Z-Wave Switch Generic driver (the 10.00 is a different story), but it would be nice to be able to use the advanced settings. I know this is not very much information to go on, I'm happy to debug further. Since I am the first one reporting this, there must be something specific to my setup I guess, but I can't put my finger on it. The obvious thing would be the older hub.

**Comment by krlaframboise** [comment]
I'll contact Zooz to get the latest firmware and get back to you later this week.

**Comment by krlaframboise** [comment]
I missed a part of your message the first time I read it so ignore my first reply if you saw it.

I wrote and tested that handler with the 1.03 firmware so that model should be working fine with the handler unless you originally tried using it with a different custom handler because that could have changed an internal setting that effects the way the device reports.

Are you able to exclude one of the ones with the 1.03 firmware, factory reset it, and then join it again to see if the custom handler works after doing that?  It couldn't hurt to reboot your hub after removing the device.

If that works then try the same for the one with the latest firmware, but if that one also isn't working with the built-in handler either then Zooz might have introduced a breaking change in the latest version so I'll still contact them about it.

**Comment by tkralphs** [comment]
> Are you able to exclude one of the ones with the 1.03 firmware, factory reset it, and then join it again to see if the custom handler works after doing that? It couldn't hurt to reboot your hub after removing the device.

I can absolutely do that and report back. I will say that I initially added the switches that have the 1.03 firmware as generic Z-wave switches and haven't used any custom drivers with them or changed any settings. Today was the first time, I thought of comparing them to the new switch, given that they have been working fine. 

One thing I noticed, which is also weird and I didn't mention above is that if I hit "up" on the switch paddle while I'm on the device page in the app, it briefly reports the button status as "toggle down" and if I hit "down," it briefly reports the button status as "Toggle up".  So it's reversed. This goes for both the 1.03 switch and the 10.00 switch.

**Comment by krlaframboise** [comment]
I spoke with Zooz and they said it sounds like a setup issue and suggested contacting their support directly at https://www.getzooz.com

**Comment by tkralphs** [comment]
Yes, I've been in touch with customer support all along. I've done quite a bit of debugging on my own (which I've told them about) and there seems to be ample evidence that there is more going on than they're hypothesizing. At the very least, there is a new firmware version. I'll get back to some more testing when I have the chance, but my son was born two days ago, so I may not get back to this for a short while.

**Comment by krlaframboise** [comment]
@tkralphs were they able to solve your problem?

**Comment by tkralphs** [comment]
I still haven't managed to find the time to do the additional debugging they've asked me to do. My newborn is taking up a lot of bandwidth :).

**Comment by tkralphs** [comment]
After a lot of finagling, I finally got the switch to function correctly with the new firmware and the existing driver. Sorry for the (apparently) fallacious bug report!
