### ISSUE TITLE
WD100 Driver and button actions

### ISSUE THREAD

**Issue by davejake** [krlaframboise/SmartThings#62]
I updated the WD100+ dimmer driver.  Now that there is only 1 button, a list of actions (i.e. up_2x), I do not see these in the options when using WebCoRE pistons.

how does the piston programming change to accommodate this?

**Comment by krlaframboise** [comment]
When setting up the trigger in WebCoRE there's an option like custom attribute/value and you need to use that instead of selecting the device as a button.  

When using that feature you'll select button for the attribute and type in the value like up_2x.

I just noticed that another user posted the same question for a different DTH so please let me know if you're able to figure out how to do it based on those instructions.

**Comment by davejake** [comment]
I appears as if the "SupportedButtonValues" is commented out our set to "false".  I may be doing something wrong, not sure how to troubleshoot

**Comment by krlaframboise** [comment]
It sounds like you found the screen I was talking about, but you should be choosing "button" as the attribute instead of "supportedButtonValues".

**Comment by davejake** [comment]
I do, but only 2 values appear as options:

![Screenshot 2022-03-29 105955](https://user-images.githubusercontent.com/10342142/160654842-fc06e82f-da50-4f86-b845-f4d2151088b1.jpg)

**Comment by krlaframboise** [comment]
What are the other options for "what kind of comparison" and what are the options when you click "Values" for "compare to" at the bottom.

**Comment by davejake** [comment]
"gets" is only option for "Kind of comparison"

and only 2 values (pushed, held) are available

**Comment by krlaframboise** [comment]
Click the word "values" next to pushed/held to see if "values" is the only option.

**Comment by davejake** [comment]
Compare to: options are: Value, Variable, Expression, Argument.

**Comment by krlaframboise** [comment]
Try expression and then type in the button action you want, like up_2x

**Comment by davejake** [comment]
I've tried your suggestion and many more.  The issue really seams to be the the "Get" command only looks for "Pushed or Held", and we need it to include the Up_2x, Down_2x etc.   Can that be programmed into the device driver?

**Comment by krlaframboise** [comment]
WebCoRE supports it as-is and it's extremely simple once you get to the correct screen.

I think the problem is that you're getting to that screen by selecting the device as a button instead  of a custom attribute because it shouldn't be asking for a button number.

I haven't used webcore in years so I'll look into it tonight and provide actual instructions for doing it...

**Comment by krlaframboise** [comment]
Start over, but after selecting "button" don’t select a button number, change the ‘compare to’ type from Value to Expression and then type in the value you need in the form "down_2x"

**Comment by davejake** [comment]
I tried, and it won’t let me do it!

 

I’ll keep messing around too.. there was another blog on your sight that blames it on SmartThings, and they tweaked your driver, but it didn’t seem to help me.

 

 

David (Jake) Jacobsen

o:952-461-6500

m:612-281-1464

**Comment by davejake** [comment]
I tried this, but it wouldn't let me do any of your suggestions.   I'll keep searching and playing

**Comment by krlaframboise** [comment]
So you've tried setting it up like below and it didn't work?  After selecting "expression" you have to type the button action wrapped with quotes in the box below it.

![image](https://user-images.githubusercontent.com/16527141/160697479-967e69ce-64c3-4a8e-84e8-faf888586825.png)
