### ISSUE TITLE
Aeotec Doorbell v 1.12

### ISSUE THREAD

**Issue by djpotts** [krlaframboise/SmartThings#9]
I was successful in getting the DH and loading it within my Smartthings Hub but the "Doorbell" shows "OFF" and I can not get an automation to trigger it, nor can I get it to show "ON" within "Things" for some reason.  I can go to the "Doorbell" and manually press any of the 3 buttons for sound but that is it.

Any suggestion/help would be great!

Thx

**Comment by krlaframboise** [comment]
Off is the device's normal state.  When the physical doorbell button is pressed or the doorbell tile in the mobile app is tapped, the doorbell will switch to on for about 1 second and then switch back to off.

Please explain how you've tried to "get an automation to trigger it".

**Comment by djpotts** [comment]
I actually figured out by playing with my automation and it now works perfectly when opening my back door with sensor! 

I do plan on placing sensor in my front door but would like to use a different file. How would I go about that? 

Thx

**Comment by krlaframboise** [comment]
I'm going to close this issue because it's not actually an issue.  

The link below goes to the forum topic for this device handler which has detailed instructions.  If you have additional questions, please post them there.

https://community.smartthings.com/t/release-aeon-labs-aeotec-doorbell/39166?u=krlaframboise
